- hosts: localhost
  tasks:
    - name: Deploy the service
      k8s:
        state: present
        definition: "{{ lookup('file', '/k8s/deployment.yml') }}"
        validate_certs: no
        namespace: default
    - name: Deploy the application
      k8s:
        state: present
        validate_certs: no
        namespace: default
        definition: "{{ lookup('file', '/k8s/service.yml') }}"
