- hosts: localhost
  tasks:
    - name: Deploy the service
      k8s:
        state: present
        definition: "{{ lookup('template', 'k8s/deployment.yml.j2') }}"
        validate_certs: no
        namespace: default
    - name: Deploy the application
      k8s:
        state: present
        validate_certs: no
        namespace: default
        src: "k8s/service.yml"
